# Uncomment the next line to define a global platform for your project
platform :ios, "9.0"

target 'Election' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Database'
  # Pods for Election

  target 'ElectionTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Firebase/Core'
  end

end
